Support disconnect/reconnect with Quorum DDS
microsoft/FluidFramework pull request #10449
Opened 2022-05-27 00:07 UTC by ChumpChief

AB#327

This change adds support for disconnect/reconnect to the Quorum DDS.  Because the resolution strategy of the Quorum already waits to hear back from the server and acknowledges that local attempts to propose may fail, this is already mostly supported.  The main change in this PR is to be selective about resubmission of ops on reconnect to simplify tracking of accepts and pending values.

Unfortunately our testing infrastructure doesn't appear to support testing of disconnect/reconnect flows particularly well outside of last-write-wins DDSs.  I add a bit of functionality to the test utils to enable more fine-grained control of disconnect timing relative to ops, and also more-realistic QuorumClients behavior so I can test a few scenarios.  The rest of the intended test scenarios I've stubbed out, but will require a more-substantial investment in our testing infrastructure to implement.

2022-05-27 16:41 UTC, ChumpChief commented on packages/runtime/test-runtime-utils/src/mocksForReconnection.ts
> +            this.factory.quorum.addMember(this.clientId, {});
This is still probably not sufficient -- with a shared quorum, offline clients will still see live updates to the quorum.

2022-05-31 21:04 UTC, ChumpChief commented on packages/runtime/test-runtime-utils/src/mocksForReconnection.ts
> +            this.factory.quorum.addMember(this.clientId, {});
Not planning to improve in this PR, tracking this improvement in AB#535

2022-06-03 21:30 UTC, Josmithr requested changes

2022-06-03 22:26 UTC, ChumpChief commented on packages/dds/quorum/src/test/quorum.spec.ts
> +        // eslint-disable-next-line max-len
I like the max-len rule generally, even in tests.  I only like overriding it where I think breaking the line would be worse for readability than keeping it long (which is mostly just long strings IMO).  So I'm generally fine with single-line disables.

2022-06-03 22:26 UTC, ChumpChief commented on packages/dds/quorum/src/test/quorum.spec.ts
> +        // TODO: Consider if there's any value in distinctly testing these scenarios for acceptance via
Done in latest

2022-06-03 22:27 UTC, ChumpChief commented on packages/runtime/test-runtime-utils/src/mocks.ts
> +    public processOneMessage() {
Added in latest

2022-06-03 22:51 UTC, Josmithr approved these changes

2022-06-06 17:16 UTC, merged