Remove remaining ICodeLoader Interfaces
microsoft/FluidFramework pull request #10772
Opened 2022-06-21 20:06 UTC by RishhiB

The deprecated ICodeLoader Interface should be removed.

## Approach
The interface `ICodeLoader` was deprecated a while ago in previous releases. The alternative for `ICodeLoader` interface is the `ICodeDetailsLoader` interface which can be imported from `@fluidframework/container-definitions`.

## Steps
The alternative for `ICodeLoader` interface is the `ICodeDetailsLoader` interface which can be imported from `@fluidframework/container-definitions`.

## Does this introduce a breaking change?

-   [X] Yes
-   [ ] No

## Other information or known dependencies

AB#346
PR: #9657, #8193

2022-06-21 21:04 UTC, sonalivdeshpande commented
maybe try adding `"InterfaceDeclaration_ICodeLoader": {"forwardCompat": false}` to container-definition package.json and doing a local build again

2022-06-22 19:56 UTC, sonalivdeshpande requested changes

2022-06-22 19:56 UTC, sonalivdeshpande commented on packages/common/container-definitions/src/test/types/validateContainerDefinitionsPrevious.ts
> -declare function get_old_InterfaceDeclaration_ICodeLoader():
was this file change manually? can you try reverting this file changes and do a local build again?

test/types/** files are auto generated on build

2022-06-23 18:08 UTC, sonalivdeshpande approved these changes

2022-06-23 18:09 UTC, sonalivdeshpande commented on BREAKING.md
> +- [Remove ICodeLoader from container-definitions](#Remove-ICodeLoader-from-container-definitions)
nits: [Remove ICodeLoader from `@fluidframework/container-definitions`]

2022-06-23 18:17 UTC, sonalivdeshpande commented on BREAKING.md
> +- [Remove ICodeLoader from @fluidframework/container-definitions](#Remove-ICodeLoader-from-container-definitions)
this is part of 1.0.0 breaking changes. this should this be included under 2.0.0 breaking change section :) 

link needs to be fixed here: 
- [Remove ICodeLoader from `@fluidframework/container-definitions`](#Remove-ICodeLoader-from-fluidframeworkcontainer-definitions)

2022-06-23 18:18 UTC, sonalivdeshpande commented on BREAKING.md
> +### Remove ICodeLoader from container-definitions
here as well -- - Remove ICodeLoader from `@fluidframework/container-definitions`

2022-06-23 18:19 UTC, scottn12 approved these changes
Looks good! Just a couple nits below and we should be good to go!

2022-06-23 18:19 UTC, scottn12 commented on BREAKING.md
> +`ICodeLoader` in `@fluidframework/container-definitions` was deprecated a while ago and is now removed. Use `ICodeDetailsLoader` by importing it from `@fluidframework/container-loader`.
Nits:

> `ICodeLoader` in `@fluidframework/container-definitions` was deprecated a while ago and is now removed.

Can we replace "a while ago" with the exact version? Either that or just remove it all together

```suggestion
`ICodeLoader` in `@fluidframework/container-definitions` was deprecated a while ago and is now removed. Use `ICodeDetailsLoader` from `@fluidframework/container-loader` instead.
```

2022-06-23 18:19 UTC, scottn12 commented on BREAKING.md
> +Please refer to [replace ICodeLoader with ICodeDetailsLoader interface](#Replace-ICodeLoader-with-ICodeDetailsLoader-interface) for more details.
I think it's probably better to just copy the details from the section you referenced so people don't have to go searching for it

2022-06-28 22:23 UTC, sonalivdeshpande commented
Let me know if you need help merging this PR in 😃

2022-06-29 19:22 UTC, sonalivdeshpande commented
@RishhiB -- merging this pr in

2022-06-29 19:22 UTC, merged