Checkpoints Collection TTL
microsoft/FluidFramework pull request #15516
Opened 2023-05-09 16:57 UTC by kekachmar

## Description

> This creates a Time-To-Live value for all documents stored in the checkpoints collection by adding a TTL index.

2023-05-09 17:03 UTC, pradeepvairamani approved these changes

2023-05-09 17:23 UTC, zhangxin511 commented on server/routerlicious/kubernetes/routerlicious/templates/fluid-configmap.yaml
> +            "checkpointsTTL": 864000
Just nit, maybe do `checkpointsTTLInSeconds`?

2023-05-09 17:23 UTC, zhangxin511 commented on server/routerlicious/packages/routerlicious-base/src/alfred/runnerFactory.ts
> +        const checkpointsTTLSeconds = config.get("checkpoints:checkpointsTTL");
Nit, add a default or throw here for invalid/missing configs?

2023-06-02 20:32 UTC, tylerbutler requested changes
This PR seems to have a lot of unrelated changes, especially outside of the server folder. Can you please rebase on the latest main before continuing?

2023-07-17 19:52 UTC, closed without merging