build(test-utils): use fluid-tsc
microsoft/FluidFramework pull request #19916
Opened 2024-03-01 22:13 UTC by DLehenbauer

Semi-automatic PR to switch to fluid-tsc

2024-03-05 18:45 UTC, RishhiB approved these changes

2024-03-05 22:56 UTC, jason-ha requested changes

2024-03-05 22:56 UTC, jason-ha commented on packages/test/test-utils/package.json
>  		"test:mocha": "npm run test:mocha:esm && echo skipping cjs to avoid overhead - npm run test:mocha:cjs",
c8 coverage settings should be adjusted to lib

2024-03-07 00:24 UTC, jason-ha approved these changes

2024-03-07 00:57 UTC, merged