build(todo): use node16 module resolution
microsoft/FluidFramework pull request #20084
Opened 2024-03-12 15:21 UTC by DLehenbauer

Semi-automatic PR to switch to node16 module resolution

2024-03-12 18:28 UTC, jason-ha requested changes

2024-03-12 18:28 UTC, jason-ha commented on examples/data-objects/todo/tsconfig.json
>  			"react-dom",
It is not a good practice to build product code with test code. Test types are included below vvvv.
Although we don't have anything using it, I think this is meant to exist as an example library. Assuming not simple split now we can file a follow-up debt item.
(blocking just for visibility)

2024-03-12 20:35 UTC, jason-ha requested changes
Bring the exports back - this is an example library.
It would be nice to have something using it, but even without it is meant to be a library.

2024-03-13 15:39 UTC, DLehenbauer commented
@jason-ha - In chat, we talked about the deprecated component model and agreed to remove the exports.

AB#7442 tracks detangling src/test builds.

Could you have another look?  Thanks.

2024-03-13 17:08 UTC, jason-ha approved these changes

2024-03-13 17:10 UTC, merged