Add internal error code to NetworkError and change draining error code
microsoft/FluidFramework pull request #21429
Opened 2024-06-13 23:31 UTC by yunho-microsoft

Add a new property: internalErrorCode to NetworkError class.
It is for giving more error information beside the code property.
Also change the draining error to include this property.

2024-06-13 23:55 UTC, shubhi1092 approved these changes
Looks good to me. Just wondering why the pnpm-lock changes are needed?

2024-06-14 15:18 UTC, znewton requested changes

2024-06-14 15:18 UTC, znewton commented on pnpm-lock.yaml
This shouldn't be changed by this PR

2024-06-14 17:03 UTC, yunho-microsoft commented on pnpm-lock.yaml
Good catch. Not sure why this file get changed. Revert it back

2024-06-14 17:09 UTC, znewton approved these changes
Looks good, one comment

2024-06-14 17:09 UTC, znewton commented on server/routerlicious/packages/lambdas/src/nexus/connect.ts
> +			message: "Cluster is not available. Please retry later.",
Message says "retry later", but there is no `retryAfter` value. Should there be?

2024-06-14 17:50 UTC, merged