Remove createComponent
microsoft/FluidFramework pull request #2823
Opened 2020-07-16 19:32 UTC by vladsud

Not used.
Not implemented by anyone and not used anywhere 
It's shape is also wrong- it returns IComponent & IComponentLoadable, when in reality it needs to return IComponentRuntimeChannel.

2020-07-16 19:43 UTC, anthony-murphy approved these changes

2020-07-16 21:52 UTC, sumedhb1995 submitted a review, later dismissed

2020-07-16 22:42 UTC, heliocliu requested changes
This is being used in all the getFactory().createComponent calls; if the return type is wrong just that should be changed instead

2020-07-17 21:18 UTC, heliocliu approved these changes

2020-07-18 00:47 UTC, merged