Update Aqueduct readme to remove reference to component
microsoft/FluidFramework pull request #3201
Opened 2020-08-14 18:47 UTC by micahgodbolt

fixes #3162

2020-08-17 18:41 UTC, sumedhb1995 reviewed
Hey @micahgodbolt ! Thanks for going through the README renames. I'll defer to @skylerjokiel and @ChumpChief for approval but this is looking great!
Left a general note regarding casing. Also I think it would be super helpful to have a paragraph that clearly states the DataObject and PureDataObject are all types of different "Fluid objects" that can interact with one another. Just to make sure that readers are clear on what "Fluid object" refers to and how their cross-relationship with other "Fluid objects" is

2020-08-18 01:03 UTC, Rick-Kirkham requested changes
See specific comments. Main problem is confusion over the terms "Fluid object" and "data object".

2020-08-18 23:04 UTC, Rick-Kirkham approved these changes

2020-08-18 23:24 UTC, sumedhb1995 approved these changes

2020-08-18 23:51 UTC, merged