Tutorial rework
microsoft/FluidFramework pull request #3413
Opened 2020-08-29 00:08 UTC by ChumpChief

Reworking the tutorial based on feedback today.  Opening as a draft because I intend to look at this more on Monday with fresh eyes, but want to give folks a preview of how the pivot feels.

2020-08-30 03:18 UTC, Rick-Kirkham requested changes

2020-08-31 21:26 UTC, skylerjokiel reviewed
Great improvement!

2020-09-01 22:05 UTC, Rick-Kirkham approved these changes

2020-09-01 23:11 UTC, skylerjokiel approved these changes
🍁 Huge improvement. Let's get it in and continue to iterate. :)

2020-09-01 23:31 UTC, merged